#!/bin/bash

BLK='\033[0;30m' # Black
RED='\033[0;31m' # Red
GRN='\033[0;32m' # Green
BLU='\033[0;34m' # Blue
CYA='\033[0;36m' # Cyan
WHI='\033[0;37m' # White
YEL='\033[0;33m' # Yellow
PUR='\033[0;35m' # Purple
NC='\033[0m' # No Color

#style:
BGreen='\033[1;32m'
BYellow='\033[1;33m'
BIBlue='\033[1;94m'
BIBlack='\033[1;90m'
Yellow='\033[0;33m'
NC='\e[0m'
bor='======================================================='

printf "\033c"
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`

echo -e  "$(tput setaf 2)
$BIBlack $bor $NC
                     $BGreen Welcome back!$NC
            $BIBlue`uname -srmo`$(tput setaf 1)$NC
$BIBlack $bor $NC"


neofetch

COLUMNS=3
# colors
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"

services=("sshd" "smbd"  "fail2ban" "docker"  "ufw" "clamav-freshclam" "tacticalagent" "meshagent" "wazuh-agent")
# sort services
IFS=$'\n' services=($(sort <<<"${services[*]}"))
unset IFS

service_status=()
# get status of all services
for service in "${services[@]}"; do
    service_status+=($(systemctl is-active "$service"))
done

out=""
for i in ${!services[@]}; do
    # color green if service is active, else red
    if [[ "${service_status[$i]}" == "active" ]]; then
        out+="${services[$i]}:,${green}${service_status[$i]}${undim},"
    else
        out+="${services[$i]}:,${red}${service_status[$i]}${undim},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"
echo ""
echo -e "${YEL}  Services:${NC}"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
echo ""

dImages=$(docker images -q | wc -l)

COLUMNS=3
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"
mapfile -t containers < <(docker ps -a --format '{{.Names}}\t{{.Status}}' | sort -k1 | awk '{ print $1,$2 }')
out=""
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< ${containers[i]}
    # color green if service is active, else red
    if [[ "${status}" == "Up" ]]; then
        out+="${NC}${name}:,${green}${status,,}${undim},"
    else
        out+="${RED}${name}:,${red}${status,,}${undim},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"
echo -e "${YEL}  Docker Status:"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
echo ""
echo -e "${YEL}       $dImages ${NC}Docker Images on Local Machine"
